### ISSUE TITLE
Images for UK passports don´t accept format JP2 nor JPEG 2000

### ISSUE THREAD

**Issue by espiralpy** [rgex/bondi-androidpassport-reader#1]
Hello,  I am trying to extract the image using an UK passport, the datas are extracted but when is decoding the image is throwing the next error. Do you have an idea what can I do to add the format or modify the library jj2000_imageutil.jar.

[error format.txt](https://github.com/rgex/bondi-android-passport-reader/files/409813/error.format.txt)

**Comment by rgex** [comment]
From what I know the UK passport is using jpeg and not jpeg2000 image format.  However I can not confirm since I don't own one myself. Is the error occuring while using the bondi app of the play store?

**Comment by espiralpy** [comment]
The error appear for playstore app and running the code of this repo. 

Then this library not convert the jpg format? I would need to add my own code to detect it?

**Comment by rgex** [comment]
I've created a new branch that is called fix-number-of-feature-points-count and where the issue is hopefully fixed.

If this isn't the case it would be great that you you could send me (panda@panda.cat) the outputs "Facial record header:" and "Number of feature points:" from the console.

**Comment by espiralpy** [comment]
Hello, I have tried the fix, but still crashing in the same point over JJ200Decoder class . I attach you  the output console. Also I noticed in Iso19794Parser.class ...for a Polish passport the  Number of feature points: 0 and is working. While a UK passport Number of feature points: 2 and not working. Maybe the count features?

try {
               org.jmrtd.jj2000.Bitmap jj2000image = JJ2000Decoder.decode(
               new ByteArrayInputStream(
               Arrays.copyOfRange(this.rawData, cursor, this.rawData.length) )
                );

[error format.txt](https://github.com/rgex/bondi-android-passport-reader/files/412416/error.format.txt)

**Comment by rgex** [comment]
Actualy I was wrong Number of feature points is not the problem. It was decodeByteArray(byte[] data, int offset, int length) I wrongly assumed it was (data, from, to).
I a new commit to the branch. It should work now ;)

**Comment by espiralpy** [comment]
Great! Currently the fix is working for UK passports. Thanks for help!, I was blocked how to read the image . Would be good to do the merge to master branch for future users.  I will keep working on this and let you know if I find other issues. Regards :) .
