### ISSUE TITLE
Unable to read US passport

### ISSUE THREAD

**Issue by shwetankb11** [rgex/bondi-androidpassport-reader#4]
Hello,

I am trying to read US Passport and it's not working.
Please, Can you identify what is the issue here?

**Comment by rgex** [comment]
Hello shwetankb11,
A few questions to help locate the issue:
From which year is the passport?
Does it detect the NFC chip?
Is there an error message, or any logs you can provide?
Have you tried with another app such as ReadID?

I'll be happy to help.
Jan

**Comment by shwetankb11** [comment]
Thanks for the quick response 
PFA of error screen
![image001](https://user-images.githubusercontent.com/20697399/34033516-8bfd547a-e1a0-11e7-9335-423511eed274.jpg)

Date of Issue of Passport: 26/02/2010 
yes, I tried the ReadID and its working fine.

**Comment by rgex** [comment]
Is the progress bar moving and then stops?
If you know how to use Android Studio (and to debug an App) It would be very helpful to send me the stack trace you get there to my email address panda at panda.cat I need only the last 5 lines or so, there should be a more detailed error message displayed there.

Otherwise I will just update the App in order to make it display more specific error messages.

**Comment by shwetankb11** [comment]
Please update the specific error messages.
Meanwhile, I will try to get the Logs from Android studio.

**Comment by shwetankb11** [comment]
Hello,
We are getting the following exception.
Card Service Exception : Mutual authentication failed: expected length: 40 + 2, actual length: 2 (SW = 0x6985: CONDITIONS NOT SATISFIED).
Also can you please update your application so that we can have the exact location of the error.
Thanks

**Comment by rgex** [comment]
Thank you shwetankb11, can you give me the 10 log outputs above the exceptions? That would be even more helpful :)

**Comment by rgex** [comment]
The exception also seems to come from another passport reading app, are you sure you ran mine?
It basically says that the session init failed, this could be due because the passport number, date of birth/expiry, was incorrect.

**Comment by shwetankb11** [comment]
Hi, 
I just have a question that 
will I get the logs from your application which is downloaded from play store?

**Comment by shwetankb11** [comment]
Hello @rgex,
I am successfully able to read US passport, Previously I was trying to read passport the wrong way
Thank you very much for your support.

**Comment by AndreiWedextim** [comment]
Hey, @shwetankb11. Could you please tell me, how did you solve this issue (Mutual authentication failed: expected length: 40 + 2, actual length: 2 (SW = 0x6985: CONDITIONS NOT SATISFIED))? I'm facing with the same one and already out of ideas, what can cause this problem. Your response would be much appreciated.
