### ISSUE TITLE
Performance upgrade support

### ISSUE THREAD

**Issue by dkulsh** [rgex/bondi-androidpassport-reader#6]
Hi Team,

We are from an organisation in India and are looking to use your library in our application.

First of - congratulations on having a great library. As we look towards using your library, the image load time seems high ~5 to 8 seconds.

Can you team work on improving the image read performance ? Any options available ?

**Comment by rgex** [comment]
The reading speed depends mainly on the NFC chip and the NFC reader capabilities, so it can not be improved by much.
